name: Bug Report
description: Create a report about a newly identified bug 
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: Which operating system is ORFmine installed on?
      options:
        - Unix (e.g., Ubuntu 20.04)
        - Mac OS (e.g., Big Sur 11.2.3)
        - Windows
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: ORFmine Version
      description: Enter the version of ORFmine you are using. You can find this by running `orfmine --version`.
      placeholder: 2.0.0
    validations:
      required: true
  - type: input
    id: python-version
    attributes:
      label: Python Version
      description: Which version of Python are you using with ORFmine?
      placeholder: 3.9.1
    validations:
      required: true
  - type: dropdown
    id: virtual-env
    attributes:
      label: Virtual Environment
      description: What virtual environment is being used?
      options:
        - Conda (or related)
        - venv/virtualenv
        - Docker container
        - Not using a virtual environment
    validations:
      required: true
  - type: dropdown
    id: install-method
    attributes:
      label: Installation Method
      description: How was ORFmine installed?
      options:
        - Using pip
        - From source
        - Other (please specify)
    validations:
      required: true
  - type: checkboxes
    id: program
    attributes:
      label: Affected ORFmine Program
      description: Which program is related to the bug?
      options:
        - label: ORFtrack
        - label: ORFfold
        - label: ORFdate
        - label: ORFribo
    validations:
      required: true
  - type: textarea
    id: command
    attributes:
      label: Command Executed
      description: The exact command(s) you ran when you encountered the bug.
      placeholder: "orfmine analyze --option value"
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: Bug Description
      description: What is the bug? What did you expect to happen and what actually happened?
      placeholder: "I expected ..., but instead ..."
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Provide detailed steps to reproduce the behavior.
      placeholder: "1. Execute command '...'\n2. Navigate to '...'\n3. Error occurs..."
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant Log Output
      description: Please copy and paste any relevant log output or error messages.
      placeholder: "Paste logs here."
      render: shell
    validations:
      required: false
  - type: textarea
    id: hardware-specs
    attributes:
      label: Hardware Specifications (optional)
      description: Please provide details about your hardware if relevant to the issue.
      placeholder: "CPU: 8-core, Memory: 16GB, Disk Type: SSD"
    validations:
      required: false
  - type: checkboxes
    id: agreement
    attributes:
      label: Confirmation
      description: Please confirm that you have checked for duplicates and reviewed the documentation for this issue.
      options:
        - label: I confirm I have searched for duplicates and reviewed the relevant documentation.
          required: true
