name: Bug Report
description: Create a report about a newly identified bug 
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: dropdown
    id: os
    attributes:
      label: OS system
      description: OS system ORFmine is installed on
      options:
        - Unix
        - Mac Os
        - Windows
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What ORFmine version are you using?
      options:
        - 2.0.0 (Latest)
        - 0.8.7 (Deprecated)
      default: 0
    validations:
      required: true
  - type: dropdown
    id: virtual-env
    attributes:
      label: Virtual environment
      description: Which virtual environment have you used?
      options:
        - Conda
        - Other
        - Neither
  - type: dropdown
    id: install
    attributes:
      label: ORFmine usage
      description: Please indicate how you are using ORFmine
      options:
        - Container image
        - Local installation
      default: 0
    validations:
      required: true
  - type: checkboxes
    id: program
    attributes:
      label: ORFmine Program
      description: Program related to the bug
      options:
        - label: ORFtrack
        - label: ORFfold
        - label: ORFdate
        - label: ORFribo
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: Bug description
      description: A clear and concise description of what the bug is, and eventually what you expected to happen
    validations:
      required: true
  - type: textarea
    id: to-reproduce
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
